### ISSUE TITLE
Player throws exception when playing file

### ISSUE THREAD

**Issue by greatwitenorth** [wnyc/cordova-plugin-playerhater#17]
When I try to play a song my app immediately quits. I've pulled this from the log file:

```
D/AndroidRuntime(23217): Shutting down VM
E/AndroidRuntime(23217): FATAL EXCEPTION: main
E/AndroidRuntime(23217): Process: com.ionicframework.playerhater371470, PID: 23217
E/AndroidRuntime(23217): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/AndroidRuntime(23217):    at org.prx.playerhater.wrappers.ThreadsafePlayerHater.seekTo(ThreadsafePlayerHater.java:134)
E/AndroidRuntime(23217):    at org.prx.playerhater.ipc.PlayerHaterServer.seekTo(PlayerHaterServer.java:100)
E/AndroidRuntime(23217):    at org.prx.playerhater.ipc.ServerPlayerHater.seekTo(ServerPlayerHater.java:101)
E/AndroidRuntime(23217):    at org.prx.playerhater.wrappers.BoundPlayerHater$3.onServiceConnected(BoundPlayerHater.java:210)
E/AndroidRuntime(23217):    at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1208)
E/AndroidRuntime(23217):    at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1225)
E/AndroidRuntime(23217):    at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(23217):    at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(23217):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(23217):    at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(23217):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23217):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(23217):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(23217):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
I/Process (23217): Sending signal. PID: 23217 SIG: 9
W/ActivityManager(  747):   Force finishing activity 1 com.ionicframework.playerhater371470/.MainActivity
I/WindowState(  747): WIN DEATH: Window{19bba035 u0 com.ionicframework.playerhater371470/com.ionicframework.playerhater371470.MainActivity}
I/WindowState(  747): WIN DEATH: Window{bbaae3b u0 com.ionicframework.playerhater371470/com.ionicframework.playerhater371470.MainActivity}
W/ActivityManager(  747): Exception thrown during pause
W/ActivityManager(  747): android.os.DeadObjectException
W/ActivityManager(  747):   at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager(  747):   at android.os.BinderProxy.transact(Binder.java:496)
W/ActivityManager(  747):   at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
W/ActivityManager(  747):   at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:825)
W/ActivityManager(  747):   at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2726)
W/ActivityManager(  747):   at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2583)
W/ActivityManager(  747):   at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2497)
W/ActivityManager(  747):   at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11500)
W/ActivityManager(  747):   at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11397)
W/ActivityManager(  747):   at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12081)
W/ActivityManager(  747):   at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11592)
W/ActivityManager(  747):   at com.android.server.am.ActivityManagerService.handleApplicationCrash(ActivityManagerService.java:11574)
W/ActivityManager(  747):   at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:1406)
W/ActivityManager(  747):   at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2208)
W/ActivityManager(  747):   at android.os.Binder.execTransact(Binder.java:446)
E/lowmemorykiller(  172): Error writing /proc/23217/oom_score_adj; errno=22
I/ActivityManager(  747): Process com.ionicframework.playerhater371470 (pid 23217) has died
```

I'm using a Nexus 5 running 5.1. Not really sure where to go from here.

**Comment by greatwitenorth** [comment]
Just realized this is a duplicate of issue #14.
