### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by mohamedsalehamin** [wnyc/cordova-plugin-playerhater#8]
[aapt] C:\Users\Mohamed\Desktop\test\platforms\android\ant-build\AndroidMan
ifest.xml:13: error: Error: No resource found that matches the given name (at 'r
esource' with value '@xml/playerhater').

BUILD FAILED
E:\Web\Prog\android\a\adt-bundle-windows-x86_64-20140702\sdk\tools\ant\build.xml
:653: The following error occurred while executing this line:
E:\Web\Prog\android\a\adt-bundle-windows-x86_64-20140702\sdk\tools\ant\build.xml
:698: null returned: 1

Total time: 2 seconds

[aapt]

C:\Users\Mohamed\Desktop\test\platforms\android\cordova\node_modules\q\q.js:126
        throw e;
              ^
Error code 1 for command: cmd with args: /s,/c,ant,debug,-f,C:\Users\Mohamed\Des
ktop\test\platforms\android\build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant
-gen

Error: C:\Users\Mohamed\Desktop\test\platforms\android\cordova\build.bat: Comman
d failed with exit code 8
at ChildProcess.whenDone (C:\Users\Mohamed\AppData\Roaming\npm\node_modules\
phonegap\node_modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js
:135:23)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:756:16)
at Process.ChildProcess._handle.onexit (child_process.js:823:5)

**Comment by ds8k** [comment]
Same issue here. Even better - if you uninstall the app it deletes your res folder

**Comment by mohamedsalehamin** [comment]
still waiting for help :(
